### ISSUE TITLE
Implement etcd_bootstrap_script.sh in Golang

### ISSUE THREAD

**Issue by timuthy** [gardener/etcd-custom-image#16]
**What would you like to be added**:
The current bootstrap script [etcd_bootstrap_script.sh](https://github.com/gardener/etcd-custom-image/blob/master/etcd_bootstrap_script.sh) should be replaced by a Golang based implementation.

**Why is this needed**:
The `etcd_bootstrap_script.sh` has several dependencies to OS utilities like `bash`, `curl`, etc. This makes it very hard to change to Distroless container base image in the future. The etcd project moved to Distroless for `3.6.x` (https://github.com/etcd-io/etcd/pull/13556)to reduce the attack surface and we should do the same. This will also eliminate some tedious maintenance tasks like updating base images and utilities because of reported vulnerabilities.

**Tasks**

_Project Structure_
- [x] Create project structure
- [x] Implement bootstrap script logic
- [x] Add signal handler
- [x] Add command and flags
- [x] Add readiness endpoint
- [x] Add TLS support
- [x] Add Makefile
- [x] Add Dockerfile
- [x] Add vendor directory
- [x] Add unit tests
  - [x] app
  - [x] bootstrap
  - [x] brclient
  - [x] util
  - [x] types
~~- [x] Use 3.5.6 version of etcd for etcd-wrapper.~~
- [ ] Use 3.4.26 of etcd in etcd-wrapper (See https://github.com/gardener/etcd-custom-image/issues/33). Move to the latest version of etcd in another increment (another PR). Backup-Restore continues to use the current client version.
- [x] Add hack/local-dev scripts to help ease local KIND + skaffold based tests.
- [x] CI/CD
  - [x] Pipeline definition
  - [x] Scripts
- [x] Documentation
  - [x] Ops guide
  - [x] Operator docs
  - [x] Developer docs
- [x] Security requirements:
  - [x] Change base image to distroless for both etcd-wrapper and etcd-backup-restore
  - [x] Add an init container to change the ownership of /var/etcd/data from root to nonroot user (required for existing clusters)
  - [x] Add pod security context to run all containers by default as nonroot.
- [x]  Add Dockerfile for ephemeral container which will be used for all diagnostics, this container will also be run as nonroot.
- [ ] Adapt etcd-druid and run druid integration and e2e
- [ ] Run g/g e2e tests
  - [ ] Run additional test where one of the pods is using etcd-wrapper and other two continue to use `etcd-custom-image`. This is possible during a stuck software update or a partially successful software update of the statefulset. Ensure that both can co-exists together.
  - [ ] Run additional test where one tries to roll-back from pods using etcd-wrapper to pods using etcd-custom-image.
